# Generated by Django 3.2.7 on 2021-10-06 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='organiser',
        ),
        migrations.AddField(
            model_name='activity',
            name='organiser_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='myActivities', related_query_name='activity', to='rest.owner'),
            preserve_default=False,
        ),
    ]
