# Generated by Django 3.2.7 on 2021-11-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20211119_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='organiser_id',
            new_name='owner',
        ),
    ]
