# Generated by Django 3.2.8 on 2021-11-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_activity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(default='old style'),
            preserve_default=False,
        ),
    ]
