# Generated by Django 3.2.8 on 2021-11-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20211122_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='activity',
            name='imageURL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='imageURL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='imageURL',
            field=models.TextField(blank=True, null=True),
        ),
    ]
